In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data_sources/unemployment analysis.csv", index_col= False)

In [3]:
df

,Country Name,Country Code,1991,1992,1993,1994,1995,1996,1997,1998,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Africa Eastern and Southern,AFE,7.80,7.84,7.85,7.84,7.83,7.84,7.86,7.81,...,6.56,6.45,6.41,6.49,6.61,6.71,6.73,6.91,7.56,8.11
1,Afghanistan,AFG,10.65,10.82,10.72,10.73,11.18,10.96,10.78,10.80,...,11.34,11.19,11.14,11.13,11.16,11.18,11.15,11.22,11.71,13.28
2,Africa Western and Central,AFW,4.42,4.53,4.55,4.54,4.53,4.57,4.60,4.66,...,4.64,4.41,4.69,4.63,5.57,6.02,6.04,6.06,6.77,6.84
3,Angola,AGO,4.21,4.21,4.23,4.16,4.11,4.10,4.09,4.07,...,7.35,7.37,7.37,7.39,7.41,7.41,7.42,7.42,8.33,8.53
4,Albania,ALB,10.31,30.01,25.26,20.84,14.61,13.93,16.88,20.05,...,13.38,15.87,18.05,17.19,15.42,13.62,12.30,11.47,13.33,11.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,Samoa,WSM,2.10,2.38,2.63,3.04,3.19,3.47,3.90,4.18,...,8.75,8.67,8.72,8.50,8.31,8.58,8.69,8.41,9.15,9.84
231,"Yemen, Rep.",YEM,8.32,8.31,8.35,8.34,8.96,9.59,10.20,10.81,...,13.17,13.27,13.47,13.77,13.43,13.30,13.15,13.06,13.39,13.57
232,South Africa,ZAF,29.95,29.98,29.92,29.89,29.89,29.87,29.91,29.95,...,24.73,24.56,24.89,25.15,26.54,27.04,26.91,28.47,29.22,33.56
233,Zambia,ZMB,18.90,19.37,19.70,18.43,16.81,15.30,13.64,12.00,...,7.85,8.61,9.36,10.13,10.87,11.63,12.01,12.52,12.85,13.03
234,Zimbabwe,ZWE,4.94,4.99,4.97,4.96,5.63,6.25,6.93,6.46,...,5.15,4.98,4.77,4.78,4.79,4.78,4.80,4.83,5.35,5.17

In [4]:
dfR = pd.read_csv("../data_sources/continents2.csv", index_col= False)

In [5]:
dfR

,name,alpha-2,alpha-3,country-code,iso_3166-2,region,sub-region,intermediate-region,region-code,sub-region-code,intermediate-region-code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Åland Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,NaN,9.0,61.0,NaN
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,NaN,2.0,15.0,NaN
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,NaN,142.0,145.0,NaN
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0

In [6]:
dfR = dfR[['alpha-3', 'region','sub-region']]
dfR

    alpha-3   region          sub-region
0       AFG     Asia       Southern Asia
1       ALA   Europe     Northern Europe
2       ALB   Europe     Southern Europe
3       DZA   Africa     Northern Africa
4       ASM  Oceania           Polynesia
..      ...      ...                 ...
244     WLF  Oceania           Polynesia
245     ESH   Africa     Northern Africa
246     YEM     Asia        Western Asia
247     ZMB   Africa  Sub-Saharan Africa
248     ZWE   Africa  Sub-Saharan Africa

[249 rows x 3 columns]

In [7]:
dftemp = pd.merge(left=df, right=dfR, left_on='Country Code', right_on='alpha-3',how='left' )

In [8]:
dftemp.columns = ['Country Name', 'Country Code', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', 'alpha-3', 'Continente', 'Sub-region']

In [9]:
dftemp = dftemp.loc[ : , ['Country Name', 'Country Code', 'Continente', 'Sub-region', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021']]

In [10]:
dftemp

,Country Name,Country Code,Continente,Sub-region,1991,1992,1993,1994,1995,1996,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Africa Eastern and Southern,AFE,NaN,NaN,7.80,7.84,7.85,7.84,7.83,7.84,...,6.56,6.45,6.41,6.49,6.61,6.71,6.73,6.91,7.56,8.11
1,Afghanistan,AFG,Asia,Southern Asia,10.65,10.82,10.72,10.73,11.18,10.96,...,11.34,11.19,11.14,11.13,11.16,11.18,11.15,11.22,11.71,13.28
2,Africa Western and Central,AFW,NaN,NaN,4.42,4.53,4.55,4.54,4.53,4.57,...,4.64,4.41,4.69,4.63,5.57,6.02,6.04,6.06,6.77,6.84
3,Angola,AGO,Africa,Sub-Saharan Africa,4.21,4.21,4.23,4.16,4.11,4.10,...,7.35,7.37,7.37,7.39,7.41,7.41,7.42,7.42,8.33,8.53
4,Albania,ALB,Europe,Southern Europe,10.31,30.01,25.26,20.84,14.61,13.93,...,13.38,15.87,18.05,17.19,15.42,13.62,12.30,11.47,13.33,11.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,Samoa,WSM,Oceania,Polynesia,2.10,2.38,2.63,3.04,3.19,3.47,...,8.75,8.67,8.72,8.50,8.31,8.58,8.69,8.41,9.15,9.84
231,"Yemen, Rep.",YEM,Asia,Western Asia,8.32,8.31,8.35,8.34,8.96,9.59,...,13.17,13.27,13.47,13.77,13.43,13.30,13.15,13.06,13.39,13.57
232,South Africa,ZAF,Africa,Sub-Saharan Africa,29.95,29.98,29.92,29.89,29.89,29.87,...,24.73,24.56,24.89,25.15,26.54,27.04,26.91,28.47,29.22,33.56
233,Zambia,ZMB,Africa,Sub-Saharan Africa,18.90,19.37,19.70,18.43,16.81,15.30,...,7.85,8.61,9.36,10.13,10.87,11.63,12.01,12.52,12.85,13.03
234,Zimbabwe,ZWE,Africa,Sub-Saharan Africa,4.94,4.99,4.97,4.96,5.63,6.25,...,5.15,4.98,4.77,4.78,4.79,4.78,4.80,4.83,5.35,5.17

Las filas con datos NaN, no son específicamente países, sino, agrupaciones de países. En la siguiente línea podemos ver los datos que contienen NaN

In [11]:
dftemp[dftemp['Continente'].isnull()]

,Country Name,Country Code,Continente,Sub-region,1991,1992,1993,1994,1995,1996,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Africa Eastern and Southern,AFE,NaN,NaN,7.80,7.84,7.85,7.84,7.83,7.84,...,6.56,6.45,6.41,6.49,6.61,6.71,6.73,6.91,7.56,8.11
2,Africa Western and Central,AFW,NaN,NaN,4.42,4.53,4.55,4.54,4.53,4.57,...,4.64,4.41,4.69,4.63,5.57,6.02,6.04,6.06,6.77,6.84
5,Arab World,ARB,NaN,NaN,11.62,12.12,12.86,12.95,13.32,12.38,...,10.66,10.74,10.87,10.97,10.76,10.90,10.50,10.01,11.49,11.63
31,Central Europe and the Baltics,CEB,NaN,NaN,9.25,10.13,11.53,11.37,10.84,10.18,...,9.98,10.05,8.95,7.82,6.49,5.30,4.32,3.78,4.37,4.50
33,Channel Islands,CHI,NaN,NaN,5.96,6.40,7.38,7.57,7.30,7.23,...,8.26,8.83,8.61,8.22,7.74,7.14,6.57,6.41,7.69,7.37
44,Caribbean small states,CSS,NaN,NaN,16.05,16.45,16.62,15.78,15.36,15.01,...,11.12,11.66,10.85,10.55,10.61,9.76,8.71,8.02,9.83,9.76
53,East Asia & Pacific (excluding high income),EAP,NaN,NaN,2.40,2.36,2.61,2.91,2.99,3.10,...,4.03,4.04,4.03,4.10,4.02,3.91,3.79,3.90,4.39,4.29
54,Early-demographic dividend,EAR,NaN,NaN,5.36,5.49,5.64,5.95,6.27,6.16,...,5.56,5.64,5.58,5.73,5.75,5.65,5.64,5.53,7.12,6.49
55,East Asia & Pacific,EAS,NaN,NaN,2.45,2.43,2.69,2.96,3.03,3.15,...,4.04,4.03,4.01,4.07,3.98,3.86,3.73,3.82,4.32,4.20
56,Europe & Central Asia (excluding high income),ECA,NaN,NaN,4.99,5.40,6.16,7.78,9.12,10.06,...,7.22,7.23,7.47,7.59,7.60,7.38,7.08,7.26,7.94,7.76
57,Europe & Central Asia,ECS,NaN,NaN,6.91,7.50,8.67,9.67,9.96,10.32,...,8.96,9.20,8.96,8.56,8.08,7.48,6.90,6.67,7.18,7.12
60,Euro area,EMU,NaN,NaN,8.25,8.89,10.68,11.76,11.44,11.67,...,11.29,11.93,11.60,10.84,10.01,9.05,8.17,7.53,7.83,7.76
65,European Union,EUU,NaN,NaN,8.50,9.23,10.82,11.50,11.06,11.10,...,10.81,11.33,10.85,10.03,9.12,8.14,7.27,6.69,7.05,7.04
66,Fragile and conflict affected situations,FCS,NaN,NaN,4.58,4.53,4.52,4.64,5.20,5.53,...,5.49,5.52,5.81,5.78,6.30,6.64,6.55,6.52,7.40,7.64
82,High income,HIC,NaN,NaN,6.75,7.32,7.85,7.85,7.45,7.42,...,7.90,7.81,7.21,6.63,6.15,5.59,5.07,4.77,6.49,5.67
85,Heavily indebted poor countries (HIPC),HPC,NaN,NaN,4.88,4.97,4.99,5.00,4.98,5.00,...,4.93,4.77,4.70,4.77,4.71,4.66,4.69,4.71,5.43,5.66
89,IBRD only,IBD,NaN,NaN,4.55,4.61,4.85,5.22,5.53,5.63,...,5.59,5.58,5.58,5.71,5.82,5.76,5.63,5.66,6.88,6.44
90,IDA & IBRD total,IBT,NaN,NaN,4.41,4.47,4.68,5.01,5.27,5.36,...,5.31,5.32,5.30,5.44,5.58,5.57,5.47,5.49,6.61,6.31
91,IDA total,IDA,NaN,NaN,3.67,3.75,3.85,3.95,3.99,4.12,...,4.23,4.30,4.24,4.43,4.70,4.88,4.92,4.89,5.70,5.87
92,IDA blend,IDB,NaN,NaN,3.06,3.16,3.32,3.54,3.63,3.88,...,3.29,3.65,3.51,4.07,5.01,5.61,5.79,5.71,6.59,6.65
94,IDA only,IDX,NaN,NaN,3.93,4.01,4.08,4.13,4.15,4.22,...,4.66,4.60,4.57,4.60,4.56,4.56,4.54,4.53,5.31,5.53
111,Latin America & Caribbean (excluding high income),LAC,NaN,NaN,5.84,5.90,5.96,6.35,7.60,7.82,...,6.38,6.29,6.08,6.66,7.89,8.18,8.05,8.09,10.16,10.12
117,Latin America & Caribbean,LCN,NaN,NaN,6.12,6.08,6.09,6.55,7.72,8.07,...,6.41,6.36,6.15,6.63,7.72,7.99,7.87,7.93,10.06,9.96
118,Least developed countries: UN classification,LDC,NaN,NaN,3.85,3.90,3.92,3.94,3.95,3.96,...,4.51,4.49,4.46,4.52,4.55,4.59,4.55,4.55,5.32,5.55
119,Low income,LIC,NaN,NaN,4.75,4.82,4.87,4.90,4.91,4.92,...,5.02,4.92,4.94,5.04,5.07,5.09,5.09,5.11,5.83,6.06
121,Lower middle income,LMC,NaN,NaN,4.75,4.84,4.94,5.16,5.33,5.36,...,5.02,5.04,5.02,5.17,5.26,5.25,5.21,5.03,6.58,5.86
122,Low & middle income,LMY,NaN,NaN,4.26,4.33,4.54,4.86,5.14,5.24,...,5.24,5.24,5.23,5.39,5.55,5.55,5.46,5.49,6.59,6.29
124,Late-demographic dividend,LTE,NaN,NaN,3.62,3.62,3.88,4.26,4.41,4.59,...,5.01,4.99,4.92,5.08,5.24,5.23,5.01,5.15,5.89,5.79
133,Middle East & North Africa,MEA,NaN,NaN,11.13,11.52,12.06,11.98,12.20,11.28,...,10.17,9.92,10.04,10.18,10.24,10.26,9.88,9.15,10.54,10.53
135,Middle income,MIC,NaN,NaN,4.22,4.29,4.52,4.86,5.16,5.26,...,5.26,5.27,5.26,5.42,5.59,5.60,5.50,5.53,6.67,6.32
140,Middle East & North Africa (excluding high inc...,MNA,NaN,NaN,11.86,12.14,12.83,12.87,13.33,12.30,...,11.75,11.48,11.67,11.93,12.05,12.07,11.62,10.77,12.24,12.19
148,North America,NAC,NaN,NaN,7.16,7.88,7.35,6.55,6.03,5.86,...,7.98,7.34,6.25,5.46,5.10,4.58,4.11,3.89,8.21,5.70
158,OECD members,OED,NaN,NaN,6.76,7.27,7.75,7.83,7.61,7.55,...,8.01,7.92,7.41,6.85,6.43,5.90,5.46,5.40,7.10,6.33
160,Other small states,OSS,NaN,NaN,11.71,12.30,13.01,13.41,13.86,14.11,...,10.73,10.87,10.66,10.61,10.61,10.28,9.92,9.79,11.01,10.98
167,Pre-demographic dividend,PRE,NaN,NaN,5.16,5.18,5.18,5.13,5.08,5.05,...,5.19,5.05,5.18,5.19,5.68,6.06,6.13,6.20,6.94,7.07
173,Pacific island small states,PSS,NaN,NaN,2.75,2.66,2.75,2.74,2.80,2.87,...,3.15,2.95,2.91,2.88,2.83,2.82,2.85,2.88,3.13,3.42
174,Post-demographic dividend,PST,NaN,NaN,6.30,6.92,7.50,7.51,7.39,7.56,...,8.06,7.96,7.44,6.87,6.40,5.84,5.29,4.95,6.70,5.81
180,South Asia,SAS,NaN,NaN,5.02,5.12,5.08,5.12,5.13,5.09,...,4.91,5.07,4.97,5.14,5.15,5.12,5.12,5.02,7.24,5.79
190,Sub-Saharan Africa (excluding high income),SSA,NaN,NaN,6.51,6.58,6.60,6.59,6.58,6.60,...,5.85,5.71,5.79,5.82,6.24,6.47,6.48,6.61,7.28,7.66
192,Sub-Saharan Africa,SSF,NaN,NaN,6.51,6.58,6.60,6.59,6.58,6.60,...,5.85,5.71,5.79,5.82,6.24,6.47,6.48,6.61,7.28,7.66
193,Small states,SST,NaN,NaN,12.27,12.77,13.30,13.36,13.57,13.66,...,10.39,10.60,10.29,10.20,10.21,9.80,9.34,9.11,10.39,10.37
202,East Asia & Pacific (IDA & IBRD countries),TEA,NaN,NaN,2.40,2.36,2.62,2.92,3.00,3.11,...,4.05,4.06,4.05,4.12,4.04,3.93,3.81,3.91,4.41,4.32
203,Europe & Central Asia (IDA & IBRD countries),TEC,NaN,NaN,5.97,6.37,7.09,8.47,9.47,10.09,...,7.53,7.59,7.66,7.63,7.45,7.09,6.69,6.78,7.40,7.27
208,Latin America & the Caribbean (IDA & IBRD coun...,TLA,NaN,NaN,5.99,5.93,5.94,6.44,7.65,8.03,...,6.42,6.37,6.18,6.68,7.80,8.09,7.98,8.04,10.20,10.09
210,Middle East & North Africa (IDA & IBRD countries),TMN,NaN,NaN,11.86,12.14,12.84,12.89,13.34,12.31,...,11.68,11.40,11.58,11.82,11.93,11.93,11.46,10.60,12.09,12.05
212,South Asia (IDA & IBRD),TSA,NaN,NaN,5.02,5.12,5.08,5.12,5.13,5.09,...,4.91,5.07,4.97,5.14,5.15,5.12,5.12,5.02,7.24,5.79
213,Sub-Saharan Africa (IDA & IBRD countries),TSS,NaN,NaN,6.51,6.58,6.60,6.59,6.58,6.60,...,5.85,5.71,5.79,5.82,6.24,6.47,6.48,6.61,7.28,7.66
220,Upper middle income,UMC,NaN,NaN,3.82,3.87,4.19,4.62,5.01,5.18,...,5.48,5.49,5.49,5.66,5.90,5.93,5.77,6.00,6.76,6.76
229,World,WLD,NaN,NaN,4.80,4.96,5.23,5.49,5.63,5.70,...,5.74,5.73,5.60,5.62,5.66,5.56,5.39,5.36,6.57,6.18

In [12]:
dftemp.to_csv("../data_sources/data_merged.csv", index= False)